---
# Source: camunda-platform/charts/identity/charts/keycloak/templates/headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: camunda-keycloak-headless
  namespace: camunda
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-7.1.6
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/component: keycloak
