---
# Source: camunda-platform/charts/identity/charts/keycloak/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: camunda-keycloak
  namespace: camunda
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-7.1.6
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
automountServiceAccountToken: true
