# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

global:
  ingress:
    enabled: true
    className: nginx
    host: "camunda.upgradingdave.com"
    tls:
      enabled: true
      secretName: "tls-secret"
  image:
    tag: 8.1.2
    # tag: latest
    # pullPolicy: Always
  identity:
    auth:
      publicIssuerUrl: "https://keycloak.upgradingdave.com/auth/realms/camunda-platform"
      identity:
        keycloak:
          url:
            protocol: "https:"
            host: "keycloak.upgradingdave.com"
            port: "443"
        contextPath: "/auth"
        auth:
          adminUser: "admin"
          existingSecret: "camunda-keycloak"
          existingSecretKey: "admin-password"
      operate:
        redirectUrl: "https://camunda.upgradingdave.com/operate"
      tasklist:
        redirectUrl: "https://camunda.upgradingdave.com/tasklist"
      optimize:
        redirectUrl: "https://camunda.upgradingdave.com/optimize"

operate:
  contextPath: "/operate"

tasklist:
  contextPath: "/tasklist"

optimize:
  contextPath: "/optimize"

identity:
  contextPath: "/identity"
  fullURL: "https://camunda.upgradingdave.com/identity"
  keycloak:
    enabled: false

zeebe-gateway:
  ingress:
    enabled: true
    className: nginx
    host: "camunda.upgradingdave.com"
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2048Mi"
      cpu: "1000m"

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 1Gi

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"

elasticsearch:
  enabled: true
  imageTag: 7.17.3
  replicas: 1
  minimumMasterNodes: 1
  # Allow no backup for single node setups
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "2Gi"






