---
# Source: camunda-platform/charts/identity/charts/keycloak/charts/postgresql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: camunda-postgresql
  namespace: camunda
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.1.9
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/component: primary
